## Numpy

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3])

arr

In [13]:
arr1 = np.array([[1,2,3,4],[3,4,5,6]])

In [14]:
arr1

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [15]:
arr2 = np.array([[1,2,3,4],[3,4,5,6,5]])

c:\users\ajay kumar\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


 ##### When we create an array shape of the two lists in the array must be same size if not it will create a list in that array array

In [16]:
arr2

array([list([1, 2, 3, 4]), list([3, 4, 5, 6, 5])], dtype=object)

In [17]:
arr2.size

2

In [24]:
arr2[:1]

array([list([1, 2, 3, 4])], dtype=object)

In [26]:
arr2[1:]
# how to access the list in this array

array([list([3, 4, 5, 6, 5])], dtype=object)

In [28]:
arr2[:]list[1:4]

SyntaxError: invalid syntax (3096979884.py, line 1)

In [21]:
arr1

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [23]:
arr1.size
# here is the diffrence between the arr1,arr2 basaed on size

8

In [36]:
arr1[:][0:2]

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [38]:
arr1[0:2][:1]

array([[1, 2, 3, 4]])

In [47]:
# create array with zeros
zeros= np.zeros(3)
zeros2 = np.zeros(7)
zeros3 = np.zeros([2,4])

In [41]:
zeros

array([0., 0., 0.])

In [42]:
zeros2

array([0., 0., 0., 0., 0., 0., 0.])

In [48]:
zeros3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

##### Creating ones

In [49]:
ones = np.ones(4)
ones2 = np.ones(7)
ones3 = np.ones([3,5])

In [50]:
ones

array([1., 1., 1., 1.])

In [51]:
ones2

array([1., 1., 1., 1., 1., 1., 1.])

In [52]:
ones3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

###### Empty array
The function empty creates an array whose initial content is random and depends on the state of the memory

In [67]:
empt = np.empty(4)
empt1 = np.empty([2,4]) # may vary
empt2= np.empty([3,5])

In [68]:
empt

array([1., 1., 1., 1.])

In [69]:
empt

array([1., 1., 1., 1.])

In [70]:
empt1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
empt2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

##### Arange

In [76]:
ar = np.arange(5)
ar

array([0, 1, 2, 3, 4])

In [79]:
ar1 = np.arange(50,100,5)
ar1

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [82]:
ar2 = np.arange(10,80,6)
ar2

array([10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76])

in arange we canot dirctly create n dimetionl array for that after creating we reshape the array

In [88]:
ak = np.arange(10,50,5).reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [90]:
ak = np.arange(10,50,5).reshape(2,4)
ak

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [94]:
ak2 = np.arange(20,100,5).reshape(8,2)
ak2

array([[20, 25],
       [30, 35],
       [40, 45],
       [50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

In [99]:
ak2.reshape(4,4)


array([[20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

##### LinSpace

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [84]:
arr4 = np.linspace(10,40,num = 10)
arr4

array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        , 33.33333333, 36.66666667, 40.        ])

In [103]:
arr5 = np.linspace(10,70,20).reshape(5,4)
arr5

array([[10.        , 13.15789474, 16.31578947, 19.47368421],
       [22.63157895, 25.78947368, 28.94736842, 32.10526316],
       [35.26315789, 38.42105263, 41.57894737, 44.73684211],
       [47.89473684, 51.05263158, 54.21052632, 57.36842105],
       [60.52631579, 63.68421053, 66.84210526, 70.        ]])

#### We can also specify a data type for the arrays

In [106]:
arr6 = np.linspace(10,200,50, dtype='int64').reshape(10,5)
arr6

array([[ 10,  13,  17,  21,  25],
       [ 29,  33,  37,  41,  44],
       [ 48,  52,  56,  60,  64],
       [ 68,  72,  75,  79,  83],
       [ 87,  91,  95,  99, 103],
       [106, 110, 114, 118, 122],
       [126, 130, 134, 137, 141],
       [145, 149, 153, 157, 161],
       [165, 168, 172, 176, 180],
       [184, 188, 192, 196, 200]], dtype=int64)

In [118]:
arr7 = np.arange(10,106,6, dtype = 'float64').reshape(4,4)
arr7

array([[ 10.,  16.,  22.,  28.],
       [ 34.,  40.,  46.,  52.],
       [ 58.,  64.,  70.,  76.],
       [ 82.,  88.,  94., 100.]])

## Adding, removing, and sorting elements

In [119]:
arr8  = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [121]:
arr8.sort()
arr8

array([1, 2, 3, 4, 5, 6, 7, 8])

In addition to sort, which returns a sorted copy of an array, you can use:

argsort, which is an indirect sort along a specified axis,

lexsort, which is an indirect stable sort on multiple keys,

searchsorted, which will find elements in a sorted array, and

partition, which is a partial sort.

In [136]:
# argsort
# in this we use specific algorithms like quick sort, merge sort etc.....................
a = np.array([[ 10,  13,  17,  21,  25],
                    [184, 188, 192, 196, 200],
       [ 29,  33,  37,  41,  44],
         [106, 110, 114, 118, 122],
       [ 48,  52,  56,  60,  64],
       [ 68,  72,  75,  79,  83],
       [ 87, 103,  91,  95,  99],
      [165, 168, 172, 176, 180],
       [126, 130, 134, 137, 141],
       [145, 149, 153, 157, 161]
       
       ])
arg =  np.argsort(a,axis = 0) Know about later

In [134]:
arg

array([[0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6],
       [3, 3, 3, 3, 3],
       [8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9],
       [7, 7, 7, 7, 7],
       [1, 1, 1, 1, 1]], dtype=int64)

concatinations

In [137]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [139]:
np.concatenate(a,b)

TypeError: only integer scalar arrays can be converted to a scalar index

In [140]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

Role of axis

In [141]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [145]:
np.concatenate((x,y),axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [147]:
np.concatenate((x,y),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

##### shape size dimention

In [149]:
arr6.shape

(10, 5)

In [150]:
arr6.size

50

In [154]:
arr6.ndim

2

##### Reshape array

In [2]:
ar = np.arange(6)
ar

array([0, 1, 2, 3, 4, 5])

In [5]:
ar = ar.reshape(3,2)
ar


array([[0, 1],
       [2, 3],
       [4, 5]])

##### convert 1 array to 2 D array

In [8]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [9]:
a.shape

(6,)

In [12]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [14]:
a2.shape

(1, 6)

You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

In [16]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

Or, for a column vector, you can insert an axis along the second dimension:

In [20]:
col_vector = a[:,np.newaxis]
col_vector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
col_vector.shape

(6, 1)

You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

In [23]:
b1 = np.expand_dims(a,axis = 1)

In [24]:
b1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [25]:
b2 = np.expand_dims(a,axis = 0)

In [26]:
b2

array([[0, 1, 2, 3, 4, 5]])

##### Indexing and slicing
You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [31]:
k = np.arange(6)
k

array([0, 1, 2, 3, 4, 5])

In [32]:
k[5]

5

In [33]:
k[2:6]

array([2, 3, 4, 5])

In [34]:
k[1:]

array([1, 2, 3, 4, 5])

In [35]:
k[-2]

4

In [37]:
k[-6:-2]

array([0, 1, 2, 3])

In [39]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.

In [40]:
print(a[a<5])

[1 2 3 4]


In [51]:
up_fives = (a>=5)
print(a[up_fives])

[ 5  6  7  8  9 10 11 12]


In [45]:
# devisible by 2
div_by_2 = a[a%2==0]
print(div_by_2)

[ 2  4  6  8 10 12]


In [47]:
# we can also use two conditions
print(a[(a<10)&(a>5)])

[6 7 8 9]


In [48]:
print(a[(a<10)|(a>5)])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [49]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


#### create an array from existing data
This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [53]:
r = np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
#1
a = r[3:7]
a

array([3, 4, 5, 6])

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

In [56]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [58]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [59]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using hsplit. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

In [62]:
x= np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [63]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

If you wanted to split your array after the third and fourth column,

In [64]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [65]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [66]:
x2 = x.copy()

In [67]:
x2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

### Basic array operations

In [72]:
data = np.array([1,2])
point = np.ones(2,dtype=int)
data

array([1, 2])

In [74]:
point

array([1, 1])

In [75]:
data+point

array([2, 3])

In [76]:
data-point

array([0, 1])

In [78]:
data*point

array([1, 2])

In [79]:
data/point

array([1., 2.])

If you want to find the sum of the elements in an array, you’d use sum(). This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [81]:
a

array([3, 4, 5, 6])

In [82]:
a.sum()

18

In [83]:
ar

array([[0, 1],
       [2, 3],
       [4, 5]])

In [84]:
ar.sum(axis=0)

array([6, 9])

In [85]:
ar.sum(axis=1)

array([1, 5, 9])

#### Broadcasting
 Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you will get a ValueError.

In [86]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

##### more Array operations

In [87]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [89]:
a.min()

0.05093587

In [90]:
a.max()

0.82485143

In [91]:
a.sum()

4.8595784

In [92]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [93]:
a.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

### Creating matrices

In [94]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [95]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
data[0,1]

2

In [97]:
data[1]

array([3, 4])

In [98]:
data[1:,:]

array([[3, 4],
       [5, 6]])

In [100]:
data[1:,0]

array([3, 5])

In [101]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
data.min(axis=0)

array([1, 2])

In [103]:
data.max(axis=1)

array([2, 4, 6])

In [105]:
#matrix operation
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data+ones

array([[2, 3],
       [4, 5]])

In [106]:
# with one row
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

In [107]:
data+ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

Be aware that when NumPy prints N-dimensional arrays, the last axis is looped over the fastest while the first axis is the slowest. For instance:

In [108]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [109]:
# random
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.2532288 , 0.74366884, 0.80909602])

In [112]:
np.random.default_rng().random(10)

array([0.94420061, 0.03266992, 0.83456243, 0.31961456, 0.14178882,
       0.50362485, 0.12415506, 0.5731274 , 0.41268574, 0.10994876])

In [113]:
np.random.rand(3)

array([0.48347942, 0.79805942, 0.29240127])

In [114]:
np.random.rand(10)

array([0.79800261, 0.74887179, 0.56167752, 0.27527609, 0.83397651,
       0.48822654, 0.38076503, 0.90083995, 0.19274552, 0.14072002])

In [116]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [117]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [118]:
np.random.rand(3,2)

array([[0.92720451, 0.97837758],
       [0.27800932, 0.96200995],
       [0.06039515, 0.78823465]])

### Generating random numbers

In [121]:
np.random.rand.integers(5,size=(2,4))

AttributeError: 'builtin_function_or_method' object has no attribute 'integers'

In [122]:
np.random.default_rng().integers(5,size=(2,4))

array([[3, 3, 1, 2],
       [4, 0, 2, 0]], dtype=int64)

#### How to get unique items and counts

In [124]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [126]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [128]:
# if we want index
unique_values,index_list = np.unique(a,return_index=True)

In [129]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [130]:
index_list

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64)

In [134]:
# if we want count
uniquev_values,occurence_count = np.unique(a,return_counts=True)
print(unique_values)
print(occurence_count)


[11 12 13 14 15 16 17 18 19 20]
[3 2 2 2 1 1 1 1 1 1]


This also works with 2D arrays!

In [136]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [137]:
np.unique(a_2d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

If you want to get the unique rows or columns, make sure to pass the axis argument. To find the unique rows, specify axis=0 and for columns, specify axis=1.

In [138]:
np.unique(a_2d,axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [139]:
np.unique(a_2d,axis = 1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [143]:
unique_values,index_values,occurence_count=np.unique(a_2d,return_index=True,return_counts=True)
print(unique_values)
print(index_values)
print(occurence_count)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[2 2 2 2 1 1 1 1 1 1 1 1]


In [144]:
# with Axis
unique_values,index_values,occurence_count=np.unique(a_2d,axis =0,return_index=True,return_counts=True)
print(unique_values)
print(index_values)
print(occurence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


#### Transposing and reshaping a matrix

In [145]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [147]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [148]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
# we can also use transpose
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [150]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [152]:
data.T
# Transpose(),T both are same

array([[1, 3, 5],
       [2, 4, 6]])

#### How to reverse an array

In [154]:
a =np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [157]:
# for 2D array
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [158]:
np.flip(a_2d)

array([[ 4,  3,  2,  1],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [161]:
# with Axis
np.flip(a_2d,axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [162]:
np.flip(a_2d,axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [ 4,  3,  2,  1]])

You can also reverse the contents of only one column or row. For example, you can reverse the contents of the row at index position 1 (the second row

In [163]:

np.flip(a_2d[1])

array([8, 7, 6, 5])

In [165]:
# reverse only 2nd row
a_2d[1]= np.flip(a_2d[1])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [171]:
a_2d[:,1]= np.flip(a_2d[:,1])
a_2d
# not correct

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [172]:
a_2d[:3,1]= np.flip(a_2d[:3,1])
a_2d

array([[ 1, 10,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  2, 11, 12],
       [ 1,  2,  3,  4]])

Reshaping and flattening multidimensional arrays

In [174]:
a_2d? #run and see