In [ ]:
import numpy as np

## Indexing and slicing

In [ ]:
q1= np.arange(10)
q2=np.arange(10,22).reshape(3,4)
q3 = np.arange(1,13).reshape(3,2,2)

In [ ]:
q1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
q2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
q3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

**Indexing on 1D array**

In [ ]:
q1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
q1[5] # it gives the sixth item

5

In [ ]:
q1[-1] # last item

9

In [ ]:
q1[0] # fist item

0

**indexing on 2D array**

In [ ]:
q2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
q2[0] # first row

array([10, 11, 12, 13])

In [ ]:
# 3rd item
q2[0,2] # row = 1, col =3

In [ ]:
q2[1,3]# row = 1, col =4

17

In [ ]:
q2[2,0]# row = 2, col =1

18

**indexing on 3D and above( Tensors)**

In [ ]:
q3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
q3[0] # gives 1st array

array([[1, 2],
       [3, 4]])

In [ ]:
q3[0,1] # give 1st array 2nd row

array([3, 4])

In [ ]:
q3[0,1,1] # 4th element

4

In [ ]:
q3[2,0,1]

10

In [ ]:
q3[1,1,1] # 2nd array 2nd row 2nd element

8

In [ ]:
q3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
# fetching the elemetnt 12
q3[2,1,1] # 3nd array 2nd row 2nd element

12

In [ ]:
q3[1,0,0]# 2nd array 1nd row 1nd element

5

**Slicing**

Slicing is the process of extracting a portion of an array.



Slicing on 1D array

In [ ]:
q1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
q1[1:4] # from 2nd eleemnt to 4th element  # slicing takes 1st index but neglects last

array([1, 2, 3])

In [ ]:
q1[4:] # from 4th eleemnt to last element

array([4, 5, 6, 7, 8, 9])

In [ ]:
q1[:6]# from first eleemnt to 6th element

array([0, 1, 2, 3, 4, 5])

In [ ]:
q1[:] # total array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
q1[-1] # last element

9

In [ ]:
# negative slicing
q1[-5:-1] # from last 5th to 2nd last

array([5, 6, 7, 8])

In [ ]:
q1[-3:] #from 3rd last to end

array([7, 8, 9])

In [ ]:
q1[:-4] # from first to last 4th

array([0, 1, 2, 3, 4, 5])

In [ ]:
# with step
q1[1:7:2] # with step 2

array([1, 3, 5])

In [ ]:
q1[::3] #total array with step 3

array([0, 3, 6, 9])

In [ ]:
q1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# negative with step
q1[-7:-2:2]

array([3, 5, 7])

**Slicing on 2Darray**

In [ ]:
q2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
q2[1,0:3] # 2nd array  1st element to 3rd

array([14, 15, 16])

In [ ]:
q2[2,:] # total 3nd array

array([18, 19, 20, 21])

In [ ]:
q2[1,:-1] #  2nd array  with out last element

array([14, 15, 16])

In [ ]:
q2[:,3] # all arrays with 4th element

array([13, 17, 21])

In [ ]:
q2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
q2[0:2,2:4] # first two arrays with 2nd and 3rd elements

array([[12, 13],
       [16, 17]])

In [ ]:
q2[:,2:4]

array([[12, 13],
       [16, 17],
       [20, 21]])

In [ ]:
q2[:,:] #total array

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
# eleemtn fetching with step
q2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
# frtching 11,13 15, 17 and 19,12
q2[:,1:4:2]

array([[11, 13],
       [15, 17],
       [19, 21]])

In [ ]:
# skipping array
# frtching 11,13  and 19,12
q2[::2,1:4:2] # skipping 2nd array

array([[11, 13],
       [19, 21]])

In [ ]:
q2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
q2[::2,::3] # skipping 2nd array and 2 values in each array after element

array([[10, 13],
       [18, 21]])

In [ ]:
q2[::2] # feching 1 and 3rd arrays

array([[10, 11, 12, 13],
       [18, 19, 20, 21]])

In [ ]:
# fetching 1st and 3rd array without 1st element in each
q2[::2,1::1]

array([[11, 12, 13],
       [19, 20, 21]])

In [ ]:
q2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

 if step=2 then 1 element skipped and if step=3  then 2 elements skipped and soon

In [ ]:
# fetching 1st and 3rd array without 1st element in each and also skip the 3rd element in each
q2[::2,1::2]

array([[11, 13],
       [19, 21]])

In [ ]:
q2


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
q2[:2,1::2]

array([[11, 13],
       [15, 17]])

slicing on 3d Array

In [ ]:
q3.ndim

3

In [ ]:
q3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
 q4 = np.arange(12,24).reshape(3,2,2)
 q4

array([[[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [ ]:
qq = np.append(q3,q4) # failed to append as matrix so we can use matri multi
qq

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
qq = qq.reshape(3,2,4)
qq

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a = np.arange(24,36).reshape(3,4)
a


array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

we want 3x3x3 matrix so we inset each array of a in each parent array of qq

In [ ]:
#  wnat to add above array to QQ for each array in the a to echa parent array in the QQ
qq = np.insert(qq,2,a[:],axis=1)  # insert array at index 2 for each parent array
qq

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [24, 25, 26, 27]],

       [[ 9, 10, 11, 12],
        [12, 13, 14, 15],
        [28, 29, 30, 31]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [32, 33, 34, 35]]])

In [ ]:
# fetch the second matrix
qq[1]

array([[ 9, 10, 11, 12],
       [12, 13, 14, 15],
       [28, 29, 30, 31]])

In [ ]:
qq[::2] # first and last matrix

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [24, 25, 26, 27]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [32, 33, 34, 35]]])

In [ ]:
qq

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [24, 25, 26, 27]],

       [[ 9, 10, 11, 12],
        [12, 13, 14, 15],
        [28, 29, 30, 31]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [32, 33, 34, 35]]])

In [ ]:
# fetch the 1st 2nd array's second row
qq[::2,1]

array([[ 5,  6,  7,  8],
       [20, 21, 22, 23]])

In [ ]:
# Fetch 2 numpy array ,middle column ---> 10,13,29
qq[1,:]

array([[ 9, 10, 11, 12],
       [12, 13, 14, 15],
       [28, 29, 30, 31]])

In [ ]:
qq[1,:,1]

array([10, 13, 29])

In [ ]:
qq

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [24, 25, 26, 27]],

       [[ 9, 10, 11, 12],
        [12, 13, 14, 15],
        [28, 29, 30, 31]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [32, 33, 34, 35]]])

In [ ]:
# Fetch 3 array--->22,23,34,35
qq[2,1:]

array([[20, 21, 22, 23],
       [32, 33, 34, 35]])

In [ ]:
qq[2,1:,2:]

array([[22, 23],
       [34, 35]])

In [ ]:
qq[2] # last matrix

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [32, 33, 34, 35]])

In [ ]:
qq[2,1:] # last two rows

array([[20, 21, 22, 23],
       [32, 33, 34, 35]])

In [ ]:
qq[2,:,2:] # last two columns

array([[18, 19],
       [22, 23],
       [34, 35]])

In [ ]:
qq[:,:,2:] # last two columns for all arrays

array([[[ 3,  4],
        [ 7,  8],
        [26, 27]],

       [[11, 12],
        [14, 15],
        [30, 31]],

       [[18, 19],
        [22, 23],
        [34, 35]]])

In [ ]:
qq

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [24, 25, 26, 27]],

       [[ 9, 10, 11, 12],
        [12, 13, 14, 15],
        [28, 29, 30, 31]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [32, 33, 34, 35]]])

In [ ]:
# fetch  1,3 and 9,11
qq[:2,:1]

array([[[ 1,  2,  3,  4]],

       [[ 9, 10, 11, 12]]])

In [ ]:
qq[:2,:1,::2]

array([[[ 1,  3]],

       [[ 9, 11]]])

In [ ]:
# fetch 1st and 3rd array
qq[::2]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [24, 25, 26, 27]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [32, 33, 34, 35]]])

In [ ]:
qq

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [24, 25, 26, 27]],

       [[ 9, 10, 11, 12],
        [12, 13, 14, 15],
        [28, 29, 30, 31]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [32, 33, 34, 35]]])

In [ ]:
# fetch 5,7 and 20,22
qq[::2,1]

array([[ 5,  6,  7,  8],
       [20, 21, 22, 23]])

In [ ]:
qq[::2,1,::2]

array([[ 5,  7],
       [20, 22]])

## Iteration through Array

In [ ]:
q1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in q1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
q2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
# Looping through 2D array
for i in q2:
  print(i)

[10 11 12 13]
[14 15 16 17]
[18 19 20 21]


In [ ]:
q3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
for j in q3:
  print(j)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


print all items in 3D using nditer ----> first convert in to 1D and applying Loop

In [ ]:
for i in np.nditer(q3):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Reshaping

## Transpose

In [ ]:
q2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
np.transpose(q2)

array([[10, 14, 18],
       [11, 15, 19],
       [12, 16, 20],
       [13, 17, 21]])

In [ ]:
# alternate method
q2.T

array([[10, 14, 18],
       [11, 15, 19],
       [12, 16, 20],
       [13, 17, 21]])

In [ ]:
q3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
q3.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

## Ravel
Converting any dimensions to 1D

In [ ]:
q2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
np.ravel(q2)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [ ]:
q3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
np.ravel(q3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
q3.ravel() # for functions in the numpy we can also directly use ()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
qq.mean()

17.833333333333332

## Stacking

In [ ]:
# Horizontal stacking
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**hstack**

for Horizantal stacking we use hstack

In [ ]:
np.hstack((z1,z2))  # for stacking all arrays must have a same shape

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

**Vstack**

for verticle stack9ng we use vstack

In [ ]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vstack((z1,z2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## splitting

its a reverse operation of stacking

In [ ]:
z1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(z1,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
np.hsplit(z1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# verticle splitting
np.vsplit(z2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]